@extends('backend.operations.layout')
@section('title', $record->reference_no ?? $record->title)
@section('operations_content')
<div class="ops-heading"><div><p class="ops-eyebrow">{{ strtoupper(str_replace('-',' ',$kind)) }}</p><h1>{{ $record->reference_no ?? $record->title }}</h1></div><span class="ops-badge">{{ $record->status }}</span></div>
@if($kind === 'production')
<section class="ops-panel"><div class="ops-metrics"><div><span>BOM version</span><strong>{{ $bom->code }} · v{{ $bom->version }}</strong></div><div><span>Planned / completed</span><strong>{{ $record->planned_qty }} / {{ $record->completed_qty }}</strong></div><div><span>Total output cost</span><strong>{{ $record->total_cost }}</strong></div></div></section>
@if($record->status === 'planned')
<section class="ops-panel"><h2>Complete production</h2><p>Enter actual consumption and outputs. Cost uses consumed stock value plus direct and overhead costs.</p>
@include('backend.operations.form_start',['formId'=>'complete-form','action'=>'production-complete/'.$record->id])<div class="ops-fields">@include('backend.operations.date')<label>Completed quantity<input name="completed_qty" type="number" step="0.0001" min="0.0001" max="{{ $record->planned_qty }}" value="{{ $record->planned_qty }}" required></label><label>Direct cost<input name="direct_cost" type="number" min="0" step="0.0001" value="0" required></label><label>Overhead cost<input name="overhead_cost" type="number" min="0" step="0.0001" value="0" required></label><label>Yield basis<select name="yield_basis"><option value="base_qty">Base quantity</option><option value="volume_cbm">Volume (CBM)</option></select></label><label>Documented waste<input name="waste_qty" type="number" min="0" step="0.000001" value="0"></label></div>
<h3>Actual consumption</h3><div class="ops-table-wrap"><table><thead><tr><th>Component</th><th>Quantity</th><th>Tracking</th></tr></thead><tbody>@foreach($components as $i=>$component)<tr><td>{{ $component->name }}<input type="hidden" name="components[{{ $i }}][bom_line_id]" value="{{ $component->id }}"></td><td><label>Consumed quantity · {{ $component->name }}<input name="components[{{ $i }}][qty]" type="number" min="0.0001" step="0.0001" value="{{ round($component->qty*$record->planned_qty/$bom->output_qty*(1+$component->scrap_percent/100),4) }}" required></label></td><td><details><summary>Tracking</summary><label>Batch ID<input name="components[{{ $i }}][product_batch_id]" type="number" min="1"></label><label>Piece ID<input name="components[{{ $i }}][stock_identity_id]" type="number" min="1"></label><label>Serial numbers<input name="components[{{ $i }}][imei_number]"></label></details></td></tr>@endforeach</tbody></table></div>
<h3>Outputs</h3><div class="ops-table-wrap"><table data-lines><thead><tr><th>Product</th><th>Quantity / cost weight</th><th>Unit</th><th>Tracking</th><th></th></tr></thead><tbody>@include('backend.operations.stock_line',['prefix'=>'outputs[0]','defaultProduct'=>(int)$bom->product_id,'defaultQty'=>$record->planned_qty,'defaultUnit'=>(int)$bom->output_uom_id,'withWeight'=>true])</tbody></table></div><button type="button" data-add-line>Add output</button>
<section><label><input type="checkbox" data-optional-lines> Recover scrap as stock</label><fieldset data-optional-group hidden disabled><h3>Recovered scrap</h3><div class="ops-table-wrap"><table data-lines><thead><tr><th>Product</th><th>Quantity / cost weight</th><th>Unit</th><th>Tracking</th><th></th></tr></thead><tbody>@include('backend.operations.stock_line',['prefix'=>'scrap_outputs[0]','withWeight'=>true])</tbody></table></div><button type="button" data-add-line>Add recovered scrap</button></fieldset></section><button type="submit" class="ops-primary">Complete production</button></form></section>
@else
<section class="ops-panel"><h2>Posted outputs</h2><div class="ops-table-wrap"><table><thead><tr><th>Product</th><th>Quantity</th><th>Value</th></tr></thead><tbody>@foreach($outputs as $output)<tr><td>{{ $output->name }}</td><td>{{ $output->qty }}</td><td>{{ $output->value }}</td></tr>@endforeach</tbody></table></div><p>Yield {{ $record->details_json['yield_percent'] ?? 0 }}% · Waste {{ $record->details_json['waste_qty'] ?? 0 }}</p>
@if($record->status === 'completed')@include('backend.operations.reverse',['reverseForm'=>'production-reverse','reverseAction'=>'production-reverse/'.$record->id])@endif</section>
@endif
@elseif($kind === 'job-work')
<section class="ops-panel"><div class="ops-metrics"><div><span>Process</span><strong>{{ $record->details_json['process']['name'] }}</strong></div><div><span>Maximum loss</span><strong>{{ $record->details_json['process']['max_loss_percent'] }}%</strong></div><div><span>Expected return</span><strong>{{ $record->expected_return_date ?? 'Not set' }}</strong></div></div><p>Material remains company-owned at its external location.</p></section>
<section class="ops-panel"><h2>Send material</h2>@include('backend.operations.form_start',['formId'=>'dispatch-form','action'=>'job-dispatch/'.$record->id])<div class="ops-fields">@include('backend.operations.warehouse')@include('backend.operations.date')</div><div class="ops-table-wrap"><table data-lines><thead><tr><th>Product</th><th>Quantity</th><th>Unit</th><th>Tracking</th><th></th></tr></thead><tbody>@include('backend.operations.stock_line',['prefix'=>'lines[0]'])</tbody></table></div><button type="button" data-add-line>Add material</button><button class="ops-primary">Send material</button></form></section>
@foreach($dispatches as $dispatch)
<section class="ops-panel"><h2>{{ $dispatch->reference_no }}</h2><p>{{ $dispatch->business_date }} · <a href="{{ url('/operations/dispatch/'.$dispatch->id.'/print') }}" target="_blank" rel="noopener">Print material document</a>@if(in_array('printing.dot_matrix',$navigation)) · <a href="{{ url('/operations/dispatch/'.$dispatch->id.'/print?format=dot_matrix') }}" target="_blank" rel="noopener">68-line output</a>@endif</p>
@if(!$dispatch->reversed_at)
@include('backend.operations.form_start',['formId'=>'receive-'.$dispatch->id,'action'=>'job-receive/'.$dispatch->id])<h3>Receive material</h3><div class="ops-fields">@include('backend.operations.warehouse',['warehouseLabel'=>'Receiving warehouse'])@include('backend.operations.date')<label>Quarantine warehouse<select name="rejected_warehouse_id"><option value="">Required for rejected material</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label></div>
<div class="ops-table-wrap"><table><thead><tr><th>Material / sent</th><th>Accepted</th><th>Rejected</th><th>Loss</th></tr></thead><tbody>@foreach($dispatchLines->get($dispatch->id,collect()) as $i=>$line)<tr><td>{{ $line->name }} · {{ $line->qty_base }}<input type="hidden" name="lines[{{ $i }}][dispatch_line_id]" value="{{ $line->id }}"></td><td><label>Accepted · {{ $line->name }}<input name="lines[{{ $i }}][accepted_qty]" type="number" min="0" step="0.0001" value="0" required></label></td><td><label>Rejected · {{ $line->name }}<input name="lines[{{ $i }}][rejected_qty]" type="number" min="0" step="0.0001" value="0" required></label></td><td><label>Loss · {{ $line->name }}<input name="lines[{{ $i }}][loss_qty]" type="number" min="0" step="0.0001" value="0" required></label></td></tr>@endforeach</tbody></table></div>
@if($record->details_json['process']['conversion'])<h3>Converted outputs</h3><div class="ops-table-wrap"><table data-lines><thead><tr><th>Product</th><th>Quantity / cost weight</th><th>Unit</th><th>Tracking</th><th></th></tr></thead><tbody>@include('backend.operations.stock_line',['prefix'=>'outputs[0]','withWeight'=>true])</tbody></table></div><button type="button" data-add-line>Add output</button>@endif
<button class="ops-primary">Receive and reconcile</button></form>@include('backend.operations.reverse',['reverseForm'=>'dispatch-reverse-'.$dispatch->id,'reverseAction'=>'job-reverse-dispatch/'.$dispatch->id,'reverseLabel'=>'dispatch'])
@else<p>Dispatch reversed: {{ $dispatch->reversal_reason }}</p>@endif
</section>@endforeach
@foreach($receipts as $receipt)<section class="ops-panel"><h2>{{ $receipt->reference_no }}</h2><p>Received {{ $receipt->details_json['received_qty'] }} · Loss {{ $receipt->details_json['loss_qty'] }} ({{ $receipt->details_json['loss_percent'] }}%)</p>
@if(!$receipt->reversed_at && !$receipt->service_purchase_id)<h3>Service bill</h3>@include('backend.operations.form_start',['formId'=>'bill-'.$receipt->id,'action'=>'job-bill/'.$receipt->id])<div class="ops-fields">@include('backend.operations.date')<label>Service product<select name="items[0][product_id]" required><option value="">Select service</option>@foreach($products->where('type','service') as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label><label>Service quantity<input name="items[0][qty]" type="number" min="0.0001" step="0.0001" value="1" required></label><label>Service unit cost<input name="items[0][net_unit_cost]" type="number" min="0" step="0.0001" required></label></div><button class="ops-primary">Create service purchase</button></form>@elseif($receipt->service_purchase_id)<p>Linked service purchase #{{ $receipt->service_purchase_id }}</p>@endif
@if(!$receipt->reversed_at)@include('backend.operations.reverse',['reverseForm'=>'receipt-reverse-'.$receipt->id,'reverseAction'=>'job-reverse-receipt/'.$receipt->id,'reverseLabel'=>'receipt'])@else<p>Receipt reversed: {{ $receipt->reversal_reason }}</p>@endif</section>@endforeach
@elseif($kind === 'project')
<section class="ops-panel"><div class="ops-metrics"><div><span>System size</span><strong>{{ $record->site_json['system_kw'] }} kW</strong></div><div><span>Revenue</span><strong>{{ $margin['revenue'] }}</strong></div><div><span>Material / service / expense</span><strong>{{ $margin['material_cost'] }} / {{ $margin['service_cost'] }} / {{ $margin['expense'] }}</strong></div><div><span>Margin</span><strong>{{ $margin['margin'] }}</strong></div></div><p>{{ $record->site_json['site_address'] }}</p></section>
<section class="ops-panel"><h2>System quotation</h2>@include('backend.operations.form_start',['formId'=>'quote-form','action'=>'project-quotation/'.$record->id])<div class="ops-fields"><label>System template<select name="bom_id" required><option value="">Select BOM</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->code }} · v{{ $template->version }}</option>@endforeach</select></label><label>System quantity<input name="qty" type="number" min="0.0001" step="0.0001" value="{{ $record->site_json['system_kw'] }}" required></label>@include('backend.operations.warehouse')@include('backend.operations.date')</div><button class="ops-primary">Create quotation / order</button></form></section>
<section class="ops-panel"><h2>Allocate serial</h2>@include('backend.operations.form_start',['formId'=>'allocate-form','action'=>'project-allocate/'.$record->id])<div class="ops-fields"><label>Available serial<select name="stock_identity_id" required><option value="">Select serial</option>@foreach($serials as $serial)<option value="{{ $serial->id }}">{{ $serial->name }} · {{ $serial->identity_no }}</option>@endforeach</select></label>@include('backend.operations.date')</div><button class="ops-primary">Allocate serial</button></form></section>
@foreach($reservations as $reservation)<section class="ops-panel"><h2>Serial {{ $reservedIdentities[$reservation->stock_identity_id] ?? $reservation->stock_identity_id }} · allocation #{{ $reservation->id }} <span class="ops-badge">{{ $reservation->status }}</span></h2>@if($reservation->status==='allocated')@include('backend.operations.form_start',['formId'=>'site-dispatch-'.$reservation->id,'action'=>'project-dispatch/'.$reservation->id])<div class="ops-fields">@include('backend.operations.date')</div><button class="ops-primary">Dispatch to site</button></form>@elseif($reservation->status==='dispatched')@include('backend.operations.form_start',['formId'=>'install-'.$reservation->id,'action'=>'project-install/'.$reservation->id])<div class="ops-fields">@include('backend.operations.date')<label>Replaces installation<select name="replaces_installation_id"><option value="">New installation</option>@foreach($installations->where('status','commissioned') as $installation)<option value="{{ $installation->id }}">Installation #{{ $installation->id }}</option>@endforeach</select></label></div><button class="ops-primary">Record installation</button></form>@elseif($reservation->status==='installed')@php($installation=$installations->firstWhere('reservation_id',$reservation->id))@include('backend.operations.form_start',['formId'=>'commission-'.$installation->id,'action'=>'project-commission/'.$installation->id])<div class="ops-fields">@include('backend.operations.date')<label>AMC months<input name="amc_months" type="number" min="0" max="1200" value="0"></label></div><button class="ops-primary">Commission and create warranty</button></form>@endif</section>@endforeach
<section class="ops-panel"><h2>Linked commercial documents</h2>
<ul>@forelse($documentLinks as $link)<li>{{ ucfirst($link->source_type) }} #{{ $link->source_id }}</li>@empty<li>No linked documents.</li>@endforelse</ul>
@include('backend.operations.form_start',['formId'=>'project-link','action'=>'project-link/'.$record->id])
<div class="ops-fields"><label>Document type<select name="source_type"><option value="sale">Sale / quotation</option><option value="purchase">Purchase</option><option value="expense">Expense</option></select></label><label>Document ID<input name="source_id" type="number" min="1" required></label></div><button class="ops-primary">Link existing document</button></form></section>
@foreach($installations as $installation)
<section class="ops-panel"><h2>Installation #{{ $installation->id }} · {{ $installation->status }}</h2>
<p>Installed {{ $installation->installed_date }} @if($installation->commissioned_date) · commissioned {{ $installation->commissioned_date }} @endif
@if($installation->replaces_installation_id) · replaces installation #{{ $installation->replaces_installation_id }} @endif</p>
<ul>@foreach($contracts->get($installation->id, collect()) as $contract)<li>{{ ucfirst($contract->kind) }}: {{ $contract->starts_on }} to {{ $contract->ends_on }} @if($contract->replaces_contract_id) · continues contract #{{ $contract->replaces_contract_id }} @endif</li>@endforeach</ul>
<h3>Service history</h3><ul>@forelse($serviceEvents->get($installation->id, collect()) as $event)<li>{{ $event->business_date }} · {{ ucfirst($event->event) }} · {{ $event->notes }}</li>@empty<li>No service events.</li>@endforelse</ul>
@include('backend.operations.form_start',['formId'=>'service-'.$installation->id,'action'=>'project-service/'.$installation->id])
<div class="ops-fields">@include('backend.operations.date')<label>Service event<select name="event"><option value="inspection">Inspection</option><option value="repair">Repair</option></select></label><label>Service notes<textarea name="notes" required maxlength="5000"></textarea></label></div><button class="ops-primary">Append service record</button></form></section>
@endforeach
<section class="ops-panel"><h2>Invoice and payment</h2><p>Issue installed serials from site warehouse #{{ $record->site_warehouse_id }}. Invoice and payment use the Sales Command Center.</p><a class="ops-link-button" href="{{ url('/sales?new=1&project_id='.$record->id) }}">Create project invoice</a></section>
@endif
@endsection
